repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/crate-ci/typos
  rev: v1.38.1
  hooks:
    - id: typos
- repo: https://github.com/nozaq/pre-commit-deno
  rev: 0.1.0
  hooks:
    - id: deno-fmt
    - id: deno-lint
- repo: local
  hooks:
    - id: deno-test
      name: deno test
      description: Run tests.
      entry: deno task test
      pass_filenames: false
      language: system
